SELECT * 
	FROM PROFIT.PRODUCTS 
    JOIN (SELECT PRODUCT_ID,AVG(RATING) AS AVERAGE FROM PROFIT.REVIEWS
    GROUP BY PROFIT.REVIEWS.PRODUCT_ID) 
    AS a 
    ON PROFIT.PRODUCTS.PRODUCT_ID=a.PRODUCT_ID 
    where a.average>3;